name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate dummy data
        run: |
          python src/generate_dummy_data.py
      - name: Prepare features
        run: |
          python -c "from feature_engineering import prepare_and_save; import os; files=[f for f in os.listdir('data/raw') if f.endswith('.csv')]; [prepare_and_save(f.replace('.csv','')) for f in files]"
      - name: Train models (fast)
        run: |
          python -c "from ml_pipeline import train_all; train_all()"
